apiVersion: apps/v1
kind: Deployment
metadata:
  name: liberty-mpmetrics
spec:
  selector:
    matchLabels:
      app: liberty
  replicas: 1
  template:
    metadata:
      labels:
        app: liberty
    spec:
      containers:
      - name: liberty
        image: sotoiwa540/liberty-mpmetrics:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
      - name: monitor
        image: sotoiwa540/monitor-mpmetrics:1.0
        imagePullPolicy: Always
        command:
        - python
        - ./monitor_mpMetrics.py
        args:
        - --host
        - localhost
        - --port
        - "9080"
        - --interval
        - "60"
        - --timeout
        - "2"
        - --delay
        - "30"
